import CustomerDashboard from '../views/customer/CustomerDashboard';
import CustomerPackages from '../views/customer/CustomerPackages';
import CustomerSupport from '../views/customer/CustomerSupport';
import AdminPackages from '../views/admin/AdminPackages';
import AdminStaff from '../views/admin/AdminStaff';
import AdminDashboard from '../views/admin/AdminDashboard';
import StaffChat from '../views/Staff/StaffChat';
import StaffCustomers from '../views/Staff/StaffCustomers';
import StaffHome from '../views/Staff/StaffHome';
export {CustomerDashboard, CustomerPackages, CustomerSupport, AdminDashboard, AdminStaff, AdminPackages,StaffChat,StaffCustomers};
